In [3]:
import numpy as np
import pandas as pd

1. How likely is it that you roll doubles when rolling two dice? **1/6, but let's simulate**

In [5]:
# array of 20,000 dice rolls
n_trials = 20_000
n_dice = 2
outcomes = [1, 2, 3, 4, 5, 6]
rolls = np.random.choice(outcomes,(n_trials, n_dice))
rolls

array([[2, 1],
       [3, 6],
       [1, 6],
       ...,
       [4, 3],
       [4, 6],
       [3, 2]])

In [6]:
# store rolls into df
rolls_df = pd.DataFrame(rolls)
rolls_df.head()

0  1
0  2  1
1  3  6
2  1  6
3  6  4
4  3  1

In [7]:
# create 'doubles' column that indicates if rolls ended up being doubles
rolls_df['doubles'] = rolls_df[0] == rolls_df[1]

In [8]:
# verify
rolls_df.head(8)

0  1  doubles
0  2  1    False
1  3  6    False
2  1  6    False
3  6  4    False
4  3  1    False
5  2  1    False
6  6  1    False
7  1  1     True

In [9]:
# mean of this column is close to the true probability
rolls_df['doubles'].mean()

0.165

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [10]:
# array of 20,000 dice rolls
n_trials = 20_000
n_coins = 8
outcomes = ['T', 'H']
# choose one of 3 outcomes, n_trials x n_coins array
flips = np.random.choice(outcomes,(n_trials, n_coins))
flips

array([['H', 'H', 'H', ..., 'H', 'T', 'T'],
       ['H', 'T', 'H', ..., 'H', 'H', 'H'],
       ['H', 'H', 'H', ..., 'H', 'H', 'H'],
       ...,
       ['H', 'H', 'T', ..., 'T', 'H', 'H'],
       ['H', 'T', 'T', ..., 'T', 'H', 'H'],
       ['T', 'H', 'T', ..., 'T', 'H', 'T']], dtype='<U1')

In [11]:
# store rolls into df
flips_df = pd.DataFrame(flips)
flips_df.head()

0  1  2  3  4  5  6  7
0  H  H  H  T  H  H  T  T
1  H  T  H  T  T  H  H  H
2  H  H  H  H  H  H  H  H
3  T  H  T  T  H  H  T  H
4  T  H  T  H  T  T  T  T

In [25]:
flips_df['three_heads'] = flips_df.apply(lambda row: (row == 'H').sum() == 3, axis=1)

Verify

In [26]:
flips_df.tail(9)

0  1  2  3  4  5  6  7  three_heads
19991  H  T  H  T  T  H  H  T        False
19992  T  H  T  H  H  T  T  T         True
19993  H  T  T  H  H  T  H  T        False
19994  H  H  H  T  H  T  H  H        False
19995  H  T  H  T  T  H  T  H        False
19996  T  T  H  T  T  T  H  H         True
19997  H  H  T  T  H  T  H  H        False
19998  H  T  T  T  T  T  H  H         True
19999  T  H  T  T  H  T  H  T         True

In [27]:
# mean of this column is close to the true probability
flips_df['three_heads'].mean()

0.21

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [84]:
n_trials = 20_000
n_selections = 2

n_web_dev_cohorts = 3
n_data_cohorts = 1
n_cohorts = n_web_dev_cohorts + n_data_cohorts

outcomes = ['W', 'D']  # Possible outcomes: 'W' and 'D'
probabilities = [ n_web_dev_cohorts / n_cohorts,
                  n_data_cohorts / n_cohorts ] 
                    # Probabilities of getting 'W' and 'D' respectively


selections = np.random.choice(outcomes, size=(n_trials, n_selections), p=probabilities)
selections

array([['W', 'D'],
       ['W', 'W'],
       ['D', 'D'],
       ...,
       ['W', 'D'],
       ['D', 'D'],
       ['W', 'W']], dtype='<U1')

In [85]:
np.unique(selections, axis = 0)

array([['D', 'D'],
       ['D', 'W'],
       ['W', 'D'],
       ['W', 'W']], dtype='<U1')

In [88]:
# store rolls into df
selections_df = pd.DataFrame(selections)
selections_df.tail()

0  1
19995  W  D
19996  D  W
19997  W  D
19998  D  D
19999  W  W

In [89]:
selections_df['two_data'] = selections_df.apply(lambda row: (row == 'D').all(), axis=1)

In [90]:
selections_df.tail()

0  1  two_data
19995  W  D     False
19996  D  W     False
19997  W  D     False
19998  D  D      True
19999  W  W     False

In [82]:
selections_df['two_data'].unique()

array([False,  True])

In [ ]:
z

In [83]:
selections_df['two_data'].mean()

0.0612

This is close to the true probability:

In [91]:
1/4 * 1/4

0.0625

4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [69]:
mu = 3
std = 1.5
stock = 17
n_trials = 50_000

weeks = np.random.normal(mu, std, size=(n_trials, 5))
weeks

array([[1.40787007e+00, 3.35195061e+00, 3.86028333e+00, 3.35693688e+00,
        2.94153901e+00],
       [3.01359178e+00, 2.24917269e+00, 1.88455080e+00, 3.52986101e+00,
        1.10500913e-03],
       [2.46849199e+00, 2.89945872e+00, 9.25412163e-01, 9.27995649e-01,
        2.02517648e+00],
       ...,
       [2.08370502e+00, 3.19765610e-01, 1.63009191e+00, 2.86315982e+00,
        3.05199719e+00],
       [9.25212888e-01, 3.23364523e+00, 4.43623772e+00, 2.61010289e+00,
        1.26571094e+00],
       [4.80204666e+00, 8.82125309e-01, 4.66110448e+00, 3.07846280e+00,
        1.11040453e+00]])

In [70]:
weeks_df = pd.DataFrame(weeks, columns=['m','t','w','th', 'f'])
weeks_df.head()

m         t         w        th         f
0  1.407870  3.351951  3.860283  3.356937  2.941539
1  3.013592  2.249173  1.884551  3.529861  0.001105
2  2.468492  2.899459  0.925412  0.927996  2.025176
3  0.807185  3.690031  5.407825  2.739325  1.714737
4  2.896334  2.106749  5.256489  1.650856  5.102769

In [71]:
# turn negatives into zeros and round all numbers
weeks_df = weeks_df.applymap(lambda x: 0 if x < 0 else x)
weeks_df.head()

m         t         w        th         f
0  1.407870  3.351951  3.860283  3.356937  2.941539
1  3.013592  2.249173  1.884551  3.529861  0.001105
2  2.468492  2.899459  0.925412  0.927996  2.025176
3  0.807185  3.690031  5.407825  2.739325  1.714737
4  2.896334  2.106749  5.256489  1.650856  5.102769

In [72]:
weeks_df['sum'] = weeks_df.sum(axis=1)
weeks_df.head()

m         t         w        th         f        sum
0  1.407870  3.351951  3.860283  3.356937  2.941539  14.918580
1  3.013592  2.249173  1.884551  3.529861  0.001105  10.678281
2  2.468492  2.899459  0.925412  0.927996  2.025176   9.246535
3  0.807185  3.690031  5.407825  2.739325  1.714737  14.359103
4  2.896334  2.106749  5.256489  1.650856  5.102769  17.013197

In [73]:
weeks_df['still_poptarts'] = (16 - weeks_df['sum']) > 0

In [74]:
weeks_df['still_poptarts'].mean()

0.61522

5. Compare Heights

    - Men have an average height of 178 cm and standard deviation of 8cm.
    - Women have a mean of 170, sd = 6cm.
    - Since you have means and standard deviations, you can use np.random.normal to generate observations.
    - If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [78]:
men_mu = 178
women_mu = 170
men_std = 8
women_std = 6
n_trials = 20_000

men = np.random.normal(men_mu, men_std, size=(n_trials))
women = np.random.normal(women_mu, women_std, size=(n_trials))

In [79]:
data = {'men': men, 'women': women}
df = pd.DataFrame(data)
df['women_is_taller'] = df['women'] > df['men']
df.head()

men       women  women_is_taller
0  168.906263  169.004201             True
1  178.636822  174.390411            False
2  184.565199  165.959529            False
3  184.521755  156.790017            False
4  180.272014  169.215521            False

In [77]:
df['women_is_taller'].mean()

0.21455

True likelihood listed below.

In [102]:
import scipy.stats as stats

men_mean = 178
men_std = 8
women_mean = 170
women_std = 6

# Calculate the z-score for a woman's height being taller than a man's height
z_score = (men_mean - women_mean) / np.sqrt(men_std**2 + women_std**2)

# Calculate the probability using the cumulative distribution function (CDF)
probability = 1 - stats.norm.cdf(z_score)

print("The likelihood that a woman is taller than a man is:", probability)

The likelihood that a woman is taller than a man is: 0.21185539858339664


6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

    What is the probability that we observe an installation issue within the first 150 students that download anaconda?

    How likely is it that 450 students all download anaconda without an issue?

In [ ]:
n_trials = 20_000
n_students = 50

outcomes = ['good', 'corrupted']
p_corrupted = 1/250
probabilities = [ 1 - p_corrupted , p_corrupted ]

selections = np.random.choice(outcomes, size=(n_trials, n_students), p=probabilities)
selections_df = pd.DataFrame(selections)
selections_df['any_corrupted'] = selections_df.apply(lambda row: (row == 'corrupted').any(),
                                                     axis=1)
selections_df['any_corrupted'].mean()



In [85]:
totals = [50, 100, 150, 450]
n_trials = 20_000
for total in totals:

    n_students = total

    outcomes = ['good', 'corrupted']
    p_corrupted = 1/250
    probabilities = [ 1 - p_corrupted , p_corrupted ] 

    selections = np.random.choice(outcomes, size=(n_trials, n_students), p=probabilities)
    selections_df = pd.DataFrame(selections)
    selections_df['any_corrupted'] = selections_df.apply(lambda row: (row == 'corrupted').any(),
                                                         axis=1)
    p_hat = selections_df['any_corrupted'].mean()
    print(f'first {total} students: {round((p_hat)*100, 2)}% likelihood of having at least 1 corruption.')

first 50 students: 18.48% likelihood of having at least 1 corruption.
first 100 students: 33.63% likelihood of having at least 1 corruption.
first 150 students: 45.14% likelihood of having at least 1 corruption.
first 450 students: 83.71% likelihood of having at least 1 corruption.


7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

    How likely is it that a food truck will show up sometime this week?

In [167]:
n_trials = 20_000
n_days = 3

outcomes = ['truck', 'no truck']
p_truck = .7
probabilities = [ p_truck , 1 - p_truck ]


trials = np.random.choice(outcomes, size=(n_trials, n_days), p=probabilities)
trials_df = pd.DataFrame(trials)
trials_df['no_trucks'] = trials_df.apply(lambda row: (row == 'no truck').all(),
                                                     axis=1)
# proportion of trials having no trucks in 3 days
print(trials_df['no_trucks'].mean())

# proportion of trials having at least 1 truck in 3 days
print(1 - trials_df['no_trucks'].mean())

0.0281
0.9719


In [169]:
# true likelyhood of no trucks
.30 ** 3

0.026999999999999996

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [227]:
n_trials = 20_000
n_people = 23

outcomes = np.arange(1, 366)

trials = np.random.choice(outcomes, size=(n_trials, n_people))
trials_df = pd.DataFrame(trials)
trials_df['not_all_distinct'] = trials_df.apply(lambda row: len(row) != len(set(row)), axis=1)

trials_df

0    1    2    3    4    5    6    7    8    9  ...   14   15   16  \
0       60  267  112   61  224   70  205  190    4   25  ...  210  129  130   
1      220  336  179  145  297   59  288  266  239  284  ...  107  168    1   
2      340   89  354  239  127  263  299  361  313  209  ...  142   28  349   
3      348   59  273  299  345  246  261  141   65  191  ...   10  265  241   
4      173  352  119   97  184   27  326    9  354  306  ...   29  103  351   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
19995  281  362   54  296   97  149   34  314  216  208  ...  194  248  247   
19996  353  232  104   69  123  364   85   37   40  233  ...  195  132  201   
19997  364  190  361   97  246  151  111  365  225  155  ...  255  284  108   
19998  320  313  343  234   30  120  243  223  352  281  ...  235  135   66   
19999  258  287  150   66  194  223  361   18  201  224  ...    9  209  209   

        17   18   19   20   21   22  not_all_distinct  
0      337   23  326  184  211  225             False  
1      150  239  201  165   59   92              True  
2      169   22  291  259   53  224              True  
3       19   34  156  341  130   14              True  
4      308  289  272  204  197  311             False  
...    ...  ...  ...  ...  ...  ...               ...  
19995  323   95  304  216  253  185              True  
19996  157  365  322  341  282   64             False  
19997  314   73   70    8   32  337             False  
19998  360   98  238  357   62  166              True  
19999   37  264  323  133  225  314              True  

[20000 rows x 24 columns]

In [231]:
totals = [10, 23, 20, 40, 50]
n_trials = 20_000
outcomes = np.arange(1, 366)


for total in totals:
    outcomes = np.arange(1, 366)

    trials = np.random.choice(outcomes, size=(n_trials, total))
    trials_df = pd.DataFrame(trials)
    trials_df['not_all_distinct'] = \
                    trials_df.apply(lambda row: len(row) != len(set(row)), axis=1)

    
    print(f"""{trials_df['not_all_distinct'].mean()} proportion of trials
            with {total} people had a common birthday""")

0.11755 proportion of trials
            with 10 people had a common birthday
0.51165 proportion of trials
            with 23 people had a common birthday
0.41345 proportion of trials
            with 20 people had a common birthday
0.8892 proportion of trials
            with 40 people had a common birthday
0.96985 proportion of trials
            with 50 people had a common birthday
